### ISSUE TITLE
I cant get your code to compile

### ISSUE THREAD

**Issue by hatsmagee** [JakeJMattson/AnyToImage#4]
Kotlin: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class tornadofx.App, unresolved supertypes: javafx.application.Application
    class tornadofx.UIComponent, unresolved supertypes: javafx.event.EventTarget

I am using 
![image](https://user-images.githubusercontent.com/27639670/96096608-a40a8180-0e95-11eb-9850-c8ddf74f35ef.png)

**Comment by JakeJMattson** [comment]
The code was originally designed to be run specifically with JDK 8, since this version still had the JavaFX dependencies packed inside. I've pushed some updates that should add support for newer versions. Let me know if you're still having issues.

**Comment by hatsmagee** [comment]
Thanks, it works great!  Thanks for making this.
